### ISSUE TITLE
Please publish this to PyPI

### ISSUE THREAD

**Issue by webknjaz** [bosswissam/pysize#13]
P. S. Would you like to have a Travis integration automating publishing to PyPI?

**Comment by bosswissam** [comment]
I'll do that asap.

Yes if you want to create a pull request - I can fill in the credits.

**Comment by webknjaz** [comment]
Great! I'll ask my mentee @serhii73 to do such PR under my supervision :)

P.S. The name of the dist on PyPI is occupied by size converter project, so it'll be required to change `name` in `setup.py` to smth else.

**Comment by serhii73** [comment]
@webknjaz and @bosswissam what do you think about https://github.com/bosswissam/pysize/pull/14 ?
