### ISSUE TITLE
Incorrect result for custom class extending from namedtuple

### ISSUE THREAD

**Issue by painyeph** [bosswissam/pysize#5]
Adding `__slots__` to subclass of namedtuple should reduce memory usage as said in https://docs.python.org/3/library/collections.html#collections.namedtuple

I tried it but found adding `__slots__` showed more memory:

```python
class PointNoSlots(namedtuple('Point', ['x', 'y'])):
    pass

class PointWithSlots(namedtuple('Point', ['x', 'y'])):
    __slots__ = ()

print(get_size(PointNoSlots(3, 4)))  # 344
print(get_size(PointWithSlots(3, 4)))  # 468
```

It is caused by two reasons:
* Instance of `PointNoSlots` contains both `__dict__` and extra array, which is not considered in `get_size`.
* In Python 3 instance of `PointWithSlots` has no `__dict__`, but in Python 2 there is a `__dict__` propery which costs no memory in instance but results a lot in `get_size`.

**Comment by painyeph** [comment]
So this is my solution:

```python
import sys
import inspect
from collections import OrderedDict, namedtuple
from pysize import get_size as get_size_old

def get_size(obj, seen=None):
    """Recursively finds size of objects in bytes"""
    size = sys.getsizeof(obj)
    if seen is None:
        seen = set()
    obj_id = id(obj)
    if obj_id in seen:
        return 0
    # Important mark as seen *before* entering recursion to gracefully handle
    # self-referential objects
    seen.add(obj_id)
    if hasattr(obj, '__dict__'):
        for cls in obj.__class__.__mro__:
            if '__dict__' in cls.__dict__:
                d = cls.__dict__['__dict__']
                if inspect.isgetsetdescriptor(d) or inspect.ismemberdescriptor(d):
                    size += get_size(obj.__dict__, seen)
                break
    if isinstance(obj, dict):
        size += sum((get_size(v, seen) for v in obj.values()))
        size += sum((get_size(k, seen) for k in obj.keys()))
    elif hasattr(obj, '__iter__') and not isinstance(obj, (str, bytes, bytearray)):
        size += sum((get_size(i, seen) for i in obj))
    return size

class CustomObject(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __str__(self):
        return self.__class__.__name__ + '(x={}, y={})'.format(self.x, self.y)

class ExtendTupeleNoSlots(namedtuple('ExtendTupeleNoSlots', ['x', 'y'])):
    pass

class ExtendTupeleWithSlots(namedtuple('ExtendTupeleWithSlots', ['x', 'y'])):
    __slots__ = ()

class ExtendStringWithDict(str):
    __slots__ = ()
    __dict__ = {'make_trouble': [0]*100}
    __str__ = lambda self: self.__class__.__name__ + '(' + repr(self) + ')'

objs = [{(1, 2): [3, 4]}, CustomObject(3, 4), ExtendTupeleNoSlots(3, 4),
       ExtendTupeleWithSlots(3, 4), ExtendStringWithDict(''), OrderedDict([(1, 2), (3, 4)])]

print(' Object                          |  Old |  New')
print(':--------------------------------|-----:|-----:')
for obj in objs:
    print(' {:31s} | {:4d} | {:4d}'.format(str(obj), get_size_old(obj), get_size(obj)))
```

In Python 2.7:

 Object                          |  Old |  New
:--------------------------------|-----:|-----:
 {(1, 2): [3, 4]}                |  512 |  512
 CustomObject(x=3, y=4)          |  444 |  444
 ExtendTupeleNoSlots(x=3, y=4)   |  344 |  392
 ExtendTupeleWithSlots(x=3, y=4) |  468 |  112
 ExtendStringWithDict('')        | 1262 |   57
 OrderedDict([(1, 2), (3, 4)])   |  384 | 1333

In Python 3.5:

 Object                          |  Old |  New
:--------------------------------|-----:|-----:
 {(1, 2): [3, 4]}                |  544 |  544
 CustomObject(x=3, y=4)          |  308 |  308
 ExtendTupeleNoSlots(x=3, y=4)   |  168 |  224
 ExtendTupeleWithSlots(x=3, y=4) |  120 |  120
 ExtendStringWithDict('')        | 1318 |   81
 OrderedDict([(1, 2), (3, 4)])   |  592 |  880

**Comment by bosswissam** [comment]
@painyeph thank you for contributing, your proposal looks good and was just merged.
